# runs on push to beta branch
name: Test Beta Releases

on:
  push:
    branches:
      - beta

jobs:
  test:
    name: Test for no breaking-change
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run beta-test.sh from ./.admin
        working-directory: ./.admin
        run: |
          chmod +x ./beta-test.sh
          ./beta-test.sh
