name: Update package

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Update package for each subdirectory
        run: |
          for dir in $(find . -mindepth 3 -maxdepth 3 -type d ! -path "./.git*"); do
            dir=${dir#./}
            echo "Updating package for $dir"
            npm update --save --pattern "@superviz/sdk"
            if [[ $dir == *"matterport"* ]]; then
              npm update --save --pattern "@superviz/matterport-plugin"
            fi
            if [[ $dir == *"autodesk"* ]]; then
              npm update --save --pattern "@superviz/autodesk-viewer-plugin"
            fi
            if [[ $dir == *"threejs"* ]]; then
              npm update --save --pattern "@superviz/threejs-plugin"
            fi
            git status
          done

      - name: Upload changes folder
        uses: actions/upload-artifact@v2
        with:
          name: changes
          path: changes

  commit:
    name: Commit changes
    runs-on: ubuntu-latest
    needs: update
    permissions:
      contents: write

    steps:
      - name: Download changes folder
        uses: actions/download-artifact@v2
        with:
          name: changes

      - run: git status

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update package
